name: Daily Check-in

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 0 点 UTC 时间执行
    - cron: '0 1 * * *'  # 每天 1 点 UTC 时间执行
    - cron: '0 2 * * *'  # 每天 2 点 UTC 时间执行
    - cron: '0 3 * * *'  # 每天 3 点 UTC 时间执行
    - cron: '0 4 * * *'  # 每天 4 点 UTC 时间执行
    - cron: '0 5 * * *'  # 每天 5 点 UTC 时间执行
    - cron: '0 6 * * *'  # 每天 6 点 UTC 时间执行
    - cron: '0 7 * * *'  # 每天 7 点 UTC 时间执行
    - cron: '0 8 * * *'  # 每天 8 点 UTC 时间执行
    - cron: '0 9 * * *'  # 每天 9 点 UTC 时间执行
    - cron: '0 10 * * *'  # 每天 10 点 UTC 时间执行
    - cron: '0 11 * * *'  # 每天 11 点 UTC 时间执行
    - cron: '0 12 * * *'  # 每天 12 点 UTC 时间执行
    - cron: '0 13 * * *'  # 每天 13 点 UTC 时间执行
    - cron: '0 14 * * *'  # 每天 14 点 UTC 时间执行
    - cron: '0 15 * * *'  # 每天 15 点 UTC 时间执行
    - cron: '0 16 * * *'  # 每天 16 点 UTC 时间执行
    - cron: '0 17 * * *'  # 每天 17 点 UTC 时间执行
    - cron: '0 18 * * *'  # 每天 18 点 UTC 时间执行
    - cron: '0 19 * * *'  # 每天 19 点 UTC 时间执行
    - cron: '0 20 * * *'  # 每天 20 点 UTC 时间执行
    - cron: '0 21 * * *'  # 每天 21 点 UTC 时间执行
    - cron: '0 22 * * *'  # 每天 22 点 UTC 时间执行
    - cron: '0 23 * * *'  # 每天 23 点 UTC 时间执行
  workflow_dispatch:


jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9.19'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install firefox

      - name: Execute script
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          python main.py
