name: Daily Check-in

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 0 点 UTC 时间执行
    - cron: '0 4 * * *'  # 每天 4 点 UTC 时间执行
    - cron: '0 8 * * *'  # 每天 8 点 UTC 时间执行
    - cron: '0 12 * * *'  # 每天 12 点 UTC 时间执行
    - cron: '0 16 * * *'  # 每天 16 点 UTC 时间执行
    - cron: '0 20 * * *'  # 每天 20 点 UTC 时间执行
  workflow_dispatch:


jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9.19'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install firefox

      - name: Execute script
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          CLASH_CONFIG_URL: ${{ secrets.CLASH_CONFIG_URL }}
        run: |
          python main.py
